# Run `conda-env create -f pysalworkshop.yml`
name: pysalworkshop
channels:
  - conda-forge
  - bokeh

dependencies:
  - python=3.6
  - pip
  - bokeh
  - cartopy
  - dask
  - descartes
  - geopandas
  - ipython
  - ipywidgets
  - jupyter
  - mplleaflet
  - jupyterlab
  - jupytext
  - nbconvert
  - networkx
  - palettable
  - pysal
  - qgrid
  - rasterio
  - scikit-learn
  - seaborn
  - statsmodels
  - xlrd
  - xlsxwriter
  - pip:
        - folium
        - geojson
        - palettable
        - libpysal
        - esda
        - mapclassify
        - giddy
        - datashader
